name = "qrai-worker"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
APP_ENV = "dev"
APP_ORIGIN = "http://localhost:5173"
REPORT_TIMEZONE = "Asia/Shanghai"

[[d1_databases]]
binding = "DB"
database_name = "qrai-db"
database_id = "f71d6def-2852-47af-ae8b-c36f2745afa6"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "qrai-bucket"

# Optional: bootstrap admin
# [vars]
# ADMIN_BOOTSTRAP_KEY = ""
